# keywork are special words that are used in the code
# and have a specific meaning in Python.
# keyword cannot we use as identifiers they are reserved words
# there are 35 keyword in python
# Examples of invalid identifiers:
# 1. 1st_variable (starts with a digit)
# 2. my-variable (contains a hyphen)
# 3. my variable (contains a space)
# 4. my@variable (contains a special character)
# 5. def (reserved keyword)
# 6. class (reserved keyword)
# 7. if (reserved keyword)
# 8. else (reserved keyword)
# 9. while (reserved keyword)
# 10. for (reserved keyword)
# 11. return (reserved keyword)
# 12. import (reserved keyword)
# 13. from (reserved keyword)
# 14. as (reserved keyword) 
# 15. global (reserved keyword)
# 16. nonlocal (reserved keyword)
# 17. try (reserved keyword)
# 18. except (reserved keyword)
# 19. finally (reserved keyword)
# 20. with (reserved keyword)
# 21. assert (reserved keyword)
# 22. raise (reserved keyword)
# 23. yield (reserved keyword)
# 24. pass (reserved keyword)
# 25. break (reserved keyword)
# 26. continue (reserved keyword)
# 27. del (reserved keyword)
# 28. lambda (reserved keyword)
# 29. async (reserved keyword)
# 30. await (reserved keyword)
# 31. True (reserved keyword)
# 32. False (reserved keyword)
# 33. None (reserved keyword)
# 34. is (reserved keyword)
# 35. in (reserved keyword)
# 36. not (reserved keyword)
# 37. and (reserved keyword)
# 38. or (reserved keyword)
